"use client";

import { useEffect, useState } from "react";
import { fillTemplate, useBuyerProfile } from "@/lib/buyer-profile";
import type { StatePlaybook } from "@/lib/setup-states";

const DIFFICULTY_COPY: Record<StatePlaybook["difficulty"], { label: string; tone: string }> = {
  easy: {
    label: "Easy",
    tone: "text-[color:var(--color-accent)] border-[color:var(--color-accent-dim)]",
  },
  moderate: {
    label: "Moderate",
    tone: "text-[color:var(--color-warn)] border-[color:var(--color-warn)]",
  },
  strict: {
    label: "Strict",
    tone: "text-[color:var(--color-danger)] border-[color:var(--color-danger)]",
  },
};

type Status = "not-started" | "preparing" | "submitted" | "issued";
const STATUS_LABEL: Record<Status, string> = {
  "not-started": "Not started",
  preparing: "Preparing application",
  submitted: "Submitted, waiting",
  issued: "License issued ✓",
};
const STATUS_TONE: Record<Status, string> = {
  "not-started": "border-[color:var(--color-line-strong)] text-[color:var(--color-fg-dim)]",
  preparing: "border-[color:var(--color-warn)] text-[color:var(--color-warn)] bg-[color:var(--color-warn-soft)]",
  submitted: "border-[color:var(--color-accent-dim)] text-[color:var(--color-accent)] bg-[color:var(--color-accent-soft)]",
  issued: "border-[color:var(--color-success-dim)] text-[color:var(--color-success)] bg-[color:var(--color-success-soft)]",
};

const STATUS_KEY_PREFIX = "tradeline.license_status.v1.";

export function StateRow({ state }: { state: StatePlaybook }) {
  const [profile] = useBuyerProfile();
  const [status, setStatus] = useState<Status>("not-started");
  const [hydrated, setHydrated] = useState(false);
  const [copied, setCopied] = useState<"sheet" | "bond" | "attorney" | null>(null);

  useEffect(() => {
    try {
      const raw = window.localStorage.getItem(STATUS_KEY_PREFIX + state.state);
      if (raw && ["not-started", "preparing", "submitted", "issued"].includes(raw)) {
        setStatus(raw as Status);
      }
    } catch {}
    setHydrated(true);
  }, [state.state]);

  const setStatusPersist = (s: Status) => {
    setStatus(s);
    try {
      window.localStorage.setItem(STATUS_KEY_PREFIX + state.state, s);
    } catch {}
  };

  /* ─── Application data sheet (copy-paste into state portal) ─── */
  const applicationSheet = fillTemplate(
    [
      `# ${state.state} debt-buyer license application — data sheet`,
      ``,
      `## Entity`,
      `- Legal name: [FIRM]`,
      `- Entity type: LLC`,
      `- Federal EIN: [EIN — fill from your IRS letter]`,
      `- Formation state: [Your LLC formation state]`,
      `- Principal: [YOUR_NAME]`,
      ``,
      `## Contact`,
      `- Business email: [EMAIL]`,
      `- Business phone: [PHONE]`,
      `- Business address: [Your registered business address]`,
      `- Registered agent: [From /app/setup/providers]`,
      ``,
      `## Business profile`,
      `- NAICS code: 522298 (All Other Nondepository Credit Intermediation)`,
      `- Description: Third-party debt buyer, [ASSET_FOCUS] portfolios`,
      `- Asset class focus: [ASSET_FOCUS]`,
      `- Typical purchase ticket: [TICKET]`,
      `- Third-party servicer: [SERVICER]`,
      `- Operations model: buy-side only (no direct consumer contact; collection runs through licensed servicer)`,
      ``,
      `## Bond`,
      `- Required amount: $${state.bondAmountUsd.toLocaleString()}`,
      `- Bond carrier: [BOND_CARRIER]`,
      `- Surety bond number: [Get from bond carrier after approval]`,
      ``,
      `## Filing fee`,
      `- Initial: $${state.filingFeeUsd}`,
      `- Annual renewal: $${state.annualRenewalFeeUsd}`,
      ``,
      `## State-specific notes`,
      `Regulator: ${state.regulatorName}`,
      `Portal: ${state.applicationUrl}`,
      `Typical timeline: ${state.typicalTimelineDays}`,
      ``,
      `(Generated by Tradeline · profile fields auto-filled from /app/profile)`,
    ].join("\n"),
    profile
  );

  /* ─── Bond carrier email (specific to this state) ─── */
  const bondSubject = `Surety bond — ${state.state} debt-buyer license · $${state.bondAmountUsd.toLocaleString()}`;
  const bondBody = fillTemplate(
    [
      `Hi,`,
      ``,
      `I need a $${state.bondAmountUsd.toLocaleString()} surety bond to satisfy ${state.state}'s debt-buyer license requirement. Quick on the entity:`,
      ``,
      `- Entity: [FIRM] (LLC)`,
      `- Principal: [YOUR_NAME]`,
      `- State: ${state.state}`,
      `- License regulator: ${state.regulatorName}`,
      `- Bond amount: $${state.bondAmountUsd.toLocaleString()}`,
      `- Initial filing target: within the next 30 days`,
      ``,
      `Could you send the underwriting application + annual premium quote? Happy to provide personal financial statements + recent tax returns once we engage.`,
      ``,
      `Best,`,
      `[YOUR_NAME]`,
      `[FIRM]`,
      `[PHONE] · [EMAIL]`,
    ].join("\n"),
    profile
  );

  /* ─── Attorney consult email (specific to this state) ─── */
  const attorneySubject = `${state.state} debt-buyer license — application sanity check`;
  const attorneyBody = fillTemplate(
    [
      `Hi,`,
      ``,
      `Need a sanity check before I submit the ${state.state} debt-buyer license application. Quick context:`,
      ``,
      `- Entity: [FIRM] (LLC), principal [YOUR_NAME]`,
      `- State: ${state.state} (regulator: ${state.regulatorName})`,
      `- Asset class focus: [ASSET_FOCUS]`,
      `- Servicing through: [SERVICER]`,
      `- Bond requirement: $${state.bondAmountUsd.toLocaleString()}`,
      `- Difficulty rating (per industry source): ${state.difficulty}`,
      ``,
      `Two specific things I want your eyes on:`,
      `1. Anything in ${state.state}'s rules that should change my buyer profile (operating posture, asset-class restrictions, NAICS code) before I file`,
      `2. ${state.collectionLicenseRequired ? "Collection-agency license — do I need it given I'm servicing through a third party?" : "Anything beyond the buyer license I should file concurrently"}`,
      ``,
      `Could we get on a 30-minute call this week?`,
      ``,
      `Best,`,
      `[YOUR_NAME]`,
      `[FIRM]`,
    ].join("\n"),
    profile
  );

  const copyTo = async (key: "sheet" | "bond" | "attorney", text: string) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(key);
      setTimeout(() => setCopied(null), 1500);
    } catch {}
  };

  const bondMailto = `mailto:?subject=${encodeURIComponent(bondSubject)}&body=${encodeURIComponent(bondBody)}`;
  const attorneyMailto = `mailto:?subject=${encodeURIComponent(attorneySubject)}&body=${encodeURIComponent(attorneyBody)}`;

  return (
    <article
      id={state.state}
      className={`rounded-xl p-6 ${
        status === "issued"
          ? "border-2 border-[color:var(--color-success-dim)] bg-[color:var(--color-success-soft)]"
          : "border border-[color:var(--color-line)] bg-[color:var(--color-bg-1)]"
      }`}
    >
      <div className="flex items-start justify-between gap-3 flex-wrap">
        <div>
          <div className="flex items-baseline gap-3 flex-wrap">
            <span className="font-mono text-3xl text-[color:var(--color-accent)]">{state.state}</span>
            <span className="text-xl text-[color:var(--color-fg)]">{state.name}</span>
          </div>
        </div>
        <div className="flex items-center gap-2 flex-wrap">
          {hydrated && (
            <select
              value={status}
              onChange={(e) => setStatusPersist(e.target.value as Status)}
              className={`font-mono text-[10px] tracking-[0.18em] uppercase px-2 py-1 rounded border bg-transparent ${STATUS_TONE[status]} cursor-pointer`}
            >
              {(["not-started", "preparing", "submitted", "issued"] as Status[]).map((s) => (
                <option key={s} value={s} className="bg-[color:var(--color-bg-1)] text-[color:var(--color-fg)]">
                  {STATUS_LABEL[s]}
                </option>
              ))}
            </select>
          )}
          <span
            className={`font-mono text-[10px] tracking-[0.2em] uppercase px-2 py-1 border rounded ${DIFFICULTY_COPY[state.difficulty].tone}`}
          >
            {DIFFICULTY_COPY[state.difficulty].label}
          </span>
        </div>
      </div>

      <p className="mt-4 text-[14px] text-[color:var(--color-fg)] leading-relaxed">
        {state.beginnerNotes}
      </p>

      <div className="mt-5 grid grid-cols-2 md:grid-cols-4 gap-px bg-[color:var(--color-line)] border border-[color:var(--color-line)]">
        <Stat
          label="Buyer license"
          value={state.buyerLicenseRequired ? "Required" : "Not required"}
          tone={state.buyerLicenseRequired ? "warn" : "ok"}
        />
        <Stat
          label="Collection license"
          value={state.collectionLicenseRequired ? "Required (if self-collect)" : "Not required"}
          tone={state.collectionLicenseRequired ? "warn" : "ok"}
        />
        <Stat label="Filing fee" value={state.filingFeeUsd === 0 ? "—" : `$${state.filingFeeUsd}`} />
        <Stat
          label="Bond"
          value={state.bondAmountUsd === 0 ? "—" : `$${state.bondAmountUsd.toLocaleString()}`}
        />
      </div>
      <div className="mt-1 grid grid-cols-2 md:grid-cols-4 gap-px bg-[color:var(--color-line)] border border-[color:var(--color-line)]">
        <Stat label="Annual renewal" value={state.annualRenewalFeeUsd === 0 ? "—" : `$${state.annualRenewalFeeUsd}`} />
        <Stat label="Timeline" value={state.typicalTimelineDays} />
        <Stat label="Regulator" value={state.regulatorName.split(",")[0]} />
        <Stat
          label="Apply at"
          value={
            <a
              href={state.applicationUrl}
              target="_blank"
              rel="noreferrer"
              className="text-[color:var(--color-accent)] hover:underline"
            >
              State portal →
            </a>
          }
        />
      </div>

      <div className="mt-6">
        <div className="font-mono text-[10px] tracking-[0.25em] text-[color:var(--color-fg-faint)] uppercase">
          Step-by-step in {state.state}
        </div>
        <ol className="mt-3 space-y-1.5 list-decimal pl-5 text-[14px] text-[color:var(--color-fg-dim)] leading-relaxed">
          {state.steps.map((step, i) => (
            <li key={i}>{step}</li>
          ))}
        </ol>
      </div>

      {state.redFlags.length > 0 && (
        <div className="mt-5 border border-[color:var(--color-line)] bg-[color:var(--color-bg-2)] p-4 rounded">
          <div className="font-mono text-[10px] tracking-[0.25em] text-[color:var(--color-warn)] uppercase">
            Heads-up before you commit
          </div>
          <ul className="mt-2 space-y-1 list-disc pl-5 text-[13px] text-[color:var(--color-fg-dim)] leading-relaxed">
            {state.redFlags.map((flag, i) => (
              <li key={i}>{flag}</li>
            ))}
          </ul>
        </div>
      )}

      {/* Action panel — generate application materials in one click */}
      <div
        className="mt-5 rounded-xl p-4"
        style={{
          background:
            "linear-gradient(var(--color-bg-1), var(--color-bg-1)) padding-box, var(--gradient-primary) border-box",
          border: "1.5px solid transparent",
        }}
      >
        <div className="font-mono text-[10px] tracking-[0.22em] uppercase text-[color:var(--color-accent)] mb-2">
          Start the {state.state} filing now
        </div>
        <p className="text-[12px] text-[color:var(--color-fg-dim)] leading-snug mb-3">
          Tradeline pre-fills the three things you need to start: the
          application data sheet (paste into the state portal), a bond-quote
          email to your surety carrier, and an attorney sanity-check email.
          Profile fields auto-fill from{" "}
          <a href="/app/profile" className="text-[color:var(--color-accent)] hover:underline">
            /app/profile
          </a>
          .
        </p>
        <div className="flex items-center gap-2 flex-wrap">
          <button
            type="button"
            onClick={() => copyTo("sheet", applicationSheet)}
            className="font-mono text-[10px] tracking-[0.18em] uppercase px-3 py-1.5 rounded text-[#0a0c14] hover:opacity-90 transition"
            style={{ background: "var(--gradient-primary)" }}
          >
            {copied === "sheet" ? "Copied ✓" : "Copy application data sheet"}
          </button>
          <a
            href={state.applicationUrl}
            target="_blank"
            rel="noreferrer"
            className="font-mono text-[10px] tracking-[0.18em] uppercase px-3 py-1.5 rounded border border-[color:var(--color-accent-dim)] text-[color:var(--color-accent)] hover:bg-[color:var(--color-accent-soft)] transition"
          >
            Open state portal ↗
          </a>
          <a
            href={bondMailto}
            className="font-mono text-[10px] tracking-[0.18em] uppercase px-3 py-1.5 rounded border border-[color:var(--color-line-strong)] hover:border-[color:var(--color-accent)] hover:text-[color:var(--color-accent)] transition"
          >
            Email bond carrier ↗
          </a>
          <a
            href={attorneyMailto}
            className="font-mono text-[10px] tracking-[0.18em] uppercase px-3 py-1.5 rounded border border-[color:var(--color-line-strong)] hover:border-[color:var(--color-accent)] hover:text-[color:var(--color-accent)] transition"
          >
            Email attorney ↗
          </a>
          <button
            type="button"
            onClick={() => copyTo("bond", `Subject: ${bondSubject}\n\n${bondBody}`)}
            className="font-mono text-[10px] tracking-[0.18em] uppercase px-3 py-1.5 rounded border border-[color:var(--color-line)] text-[color:var(--color-fg-dim)] hover:text-[color:var(--color-fg)] transition"
          >
            {copied === "bond" ? "Copied ✓" : "Copy bond email"}
          </button>
          <button
            type="button"
            onClick={() => copyTo("attorney", `Subject: ${attorneySubject}\n\n${attorneyBody}`)}
            className="font-mono text-[10px] tracking-[0.18em] uppercase px-3 py-1.5 rounded border border-[color:var(--color-line)] text-[color:var(--color-fg-dim)] hover:text-[color:var(--color-fg)] transition"
          >
            {copied === "attorney" ? "Copied ✓" : "Copy attorney email"}
          </button>
        </div>
        <p className="mt-3 text-[10px] text-[color:var(--color-fg-faint)] leading-snug">
          State license applications are filed through each state&rsquo;s online portal — not by
          email. The data sheet is the structured set of fields you&rsquo;ll paste in.
        </p>
      </div>
    </article>
  );
}

function Stat({
  label,
  value,
  tone = "default",
}: {
  label: string;
  value: React.ReactNode;
  tone?: "ok" | "warn" | "default";
}) {
  const color =
    tone === "warn"
      ? "text-[color:var(--color-warn)]"
      : tone === "ok"
        ? "text-[color:var(--color-accent)]"
        : "text-[color:var(--color-fg)]";
  return (
    <div className="bg-[color:var(--color-bg-1)] p-3">
      <div className="font-mono text-[10px] tracking-[0.18em] text-[color:var(--color-fg-faint)] uppercase">
        {label}
      </div>
      <div className={`mt-1 text-[13px] font-mono ${color}`}>{value}</div>
    </div>
  );
}
