import Link from "next/link";
import type { Originator, RadarSnapshot, SecSignal } from "@/lib/snapshot";
import { talkingPointsFor } from "@/lib/talking-points";
import {
  buildBankContext,
  generateTalkingPoints,
  type TalkingPoint,
} from "@/lib/talking-points-llm";

// Async Server Component — calls the LLM at render time. Wrapped in <Suspense>
// by the parent so the rest of the page is interactive while this resolves.
export async function LLMTalkingPoints({
  ticker,
  snap,
  signals,
  originator,
}: {
  ticker: string;
  snap: RadarSnapshot;
  signals: SecSignal[];
  originator: Originator;
}) {
  const context = buildBankContext(originator, snap);
  const result = await generateTalkingPoints(context);

  if (result.kind === "ok") {
    return (
      <SectionShell
        ticker={ticker}
        source="llm"
        points={result.points}
        note={
          <>
            Generated by Claude Sonnet 4.6 at render time, using your live snapshot for{" "}
            <strong>{ticker}</strong>. Re-renders on every view; cached at the edge for 5 minutes.
          </>
        }
      />
    );
  }

  // Fallback to template-driven points when the LLM is unavailable
  const fallback = talkingPointsFor(originator, signals);
  const noticeTone =
    result.kind === "disabled"
      ? "text-[color:var(--color-fg-faint)]"
      : "text-[color:var(--color-warn)]";
  const notice =
    result.kind === "disabled" ? (
      <>
        LLM-generated talking points are disabled. Set{" "}
        <code className="font-mono text-[12px] text-[color:var(--color-fg)]">
          ANTHROPIC_API_KEY
        </code>{" "}
        on the server to enable Claude-Sonnet generation. Showing template-based scaffolding below.
      </>
    ) : (
      <>
        LLM call failed: <code className="font-mono text-[12px]">{result.message}</code>. Showing
        template-based fallback below.
      </>
    );

  return (
    <SectionShell
      ticker={ticker}
      source="template"
      points={fallback}
      note={<span className={noticeTone}>{notice}</span>}
    />
  );
}

// Skeleton shown while the LLM call is in flight. Uses the same shape as the
// real cards so layout doesn't shift when content arrives.
export function LLMTalkingPointsSkeleton({ ticker }: { ticker: string }) {
  return (
    <section className="mb-12">
      <SectionLabel>Sales angles · what to say about {ticker}</SectionLabel>
      <p className="mt-2 mb-4 text-[14px] text-[color:var(--color-fg-dim)] leading-relaxed max-w-2xl">
        Generating context-aware talking points from this bank&rsquo;s current signals…
      </p>
      <div className="space-y-3">
        {[0, 1, 2].map((i) => (
          <div
            key={i}
            className="border border-[color:var(--color-line)] bg-[color:var(--color-bg-1)] p-5"
          >
            <div className="font-mono text-[10px] tracking-[0.25em] text-[color:var(--color-fg-faint)] uppercase">
              Loading scenario…
            </div>
            <div className="mt-2 h-5 w-3/4 bg-[color:var(--color-bg-2)] shimmer" />
            <div className="mt-2 h-3 w-1/2 bg-[color:var(--color-bg-2)] shimmer" />
          </div>
        ))}
      </div>
    </section>
  );
}

function SectionShell({
  ticker,
  source,
  points,
  note,
}: {
  ticker: string;
  source: "llm" | "template";
  points: TalkingPoint[];
  note: React.ReactNode;
}) {
  return (
    <section className="mb-12">
      <div className="flex items-baseline justify-between gap-3 flex-wrap">
        <SectionLabel>Sales angles · what to say about {ticker}</SectionLabel>
        <span
          className={`font-mono text-[10px] tracking-[0.2em] uppercase px-2 py-0.5 border ${
            source === "llm"
              ? "border-[color:var(--color-accent-dim)] text-[color:var(--color-accent)]"
              : "border-[color:var(--color-line-strong)] text-[color:var(--color-fg-faint)]"
          }`}
        >
          {source === "llm" ? "Sonnet 4.6" : "Templates"}
        </span>
      </div>
      <p className="mt-2 mb-4 text-[13px] text-[color:var(--color-fg-dim)] leading-relaxed max-w-2xl">
        {note}
      </p>
      <div className="space-y-3">
        {points.map((tp, i) => (
          <div
            key={i}
            className="border border-[color:var(--color-line)] bg-[color:var(--color-bg-1)] p-5"
          >
            <div className="font-mono text-[10px] tracking-[0.25em] text-[color:var(--color-fg-faint)] uppercase">
              {tp.scenario}
            </div>
            <p className="mt-2 text-[14px] text-[color:var(--color-fg)] leading-relaxed italic">
              {/^["“].*["”]$/.test(tp.line.trim()) ? tp.line : `"${tp.line}"`}
            </p>
            <p className="mt-2 text-[12px] text-[color:var(--color-fg-dim)] leading-relaxed">
              <span className="text-[color:var(--color-warn)]">Why:</span> {tp.rationale}
            </p>
          </div>
        ))}
      </div>
      <div className="mt-4">
        <Link
          href="/app/playbook"
          className="font-mono text-[11px] tracking-[0.18em] uppercase text-[color:var(--color-fg-dim)] hover:text-[color:var(--color-accent)] transition"
        >
          Full closing playbook &rarr;
        </Link>
      </div>
    </section>
  );
}

function SectionLabel({ children }: { children: React.ReactNode }) {
  return (
    <div className="font-mono text-[11px] tracking-[0.25em] text-[color:var(--color-fg-faint)] uppercase">
      {children}
    </div>
  );
}
